### ISSUE TITLE
Detail (Pnguin Style)

### ISSUE THREAD

**Issue by PenguinPlayz** [ire4ever1190/ire4ever1190.github.io#3]
Hi ire4ever1190,
I think you should do something with the backround or something to just make it a little more attracting to the eye. I really like what you have done so far with this website and I look forward to this websites progress.
Yours sincerely,
 PenguinPlayz

**Comment by ire4ever1190** [comment]
thanks for that PenguinPlayz i think i have fixed it go check it then ill close this issue
